name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Temporarily disable cache to bypass the 400 error
          # cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm ci --no-fund --no-audit
          ./build.sh
          touch out/.nojekyll
        env:
          NODE_ENV: production

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: out
          clean: true
